package Adminrozana;

import java.util.concurrent.TimeUnit;
import java.util.logging.Logger;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Select;
import org.testng.annotations.Test;

public class AutomateReports {
	@Test
	public void automateReports() throws InterruptedException {
		 Logger logger = Logger.getLogger(AutomateReports.class.getName());
		// set the path of
		System.setProperty("webdriver.chrome.driver","C:\\Users\\Ravi Ranjan\\OneDrive\\Desktop\\Chromedriver\\chromedriver.exe");
		WebDriver driver = new ChromeDriver();
			//URL
			driver.get("https://dev.rozana.in/admin");
			logger.info(driver.getTitle());
			driver.manage().window().maximize();
			driver.manage().timeouts().implicitlyWait(10000, TimeUnit.MILLISECONDS);
			// UserName/Password
			driver.findElement(By.xpath(".//input[@id='email']")).sendKeys("ravi@amithi.com");
			driver.findElement(By.xpath(".//input[@id='password']")).sendKeys("12345678");
			driver.findElement(By.xpath(".//button[@type='button']")).click();
			driver.findElement(By.xpath("//input[@type='text']")).sendKeys("8033");
			Thread.sleep(2000);
			driver.findElement(By.xpath("//button[text()='Submit']")).click();
			// Language Changes
			driver.findElement(By.xpath(".//span[@class='language']/ancestor::li[@id='lang-change']")).click();
			Thread.sleep(2000);
			driver.findElement(By.xpath("//span[text()='English']")).click();
			driver.findElement(By.xpath("//i[@class='demo-pli-bell']")).click();
			driver.findElement(By.xpath("//span[text()='Dashboard']")).click();
			String ord=driver.findElement(By.xpath("(//h2[@class='no-margin ng-binding'])[1]")).getText();
			System.out.println(ord);
			String ord1=driver.findElement(By.xpath("(//h2[@class='no-margin ng-binding'])[2]")).getText();
			System.out.println(ord1);
			String ord2=driver.findElement(By.xpath("(//h2[@class='no-margin ng-binding'])[3]")).getText();
			System.out.println(ord2);
			String ord3=driver.findElement(By.xpath("(//h2[@class='no-margin ng-binding'])[4]")).getText();
			System.out.println(ord3);
			driver.findElement(By.xpath("//span[text()='Reports']")).click();
			Thread.sleep(1000);
			driver.findElement(By.xpath("//ul//li//a//span[text()='Automate Reports']")).click();
			driver.findElement(By.xpath("//h3[text()='Management Reports']")).click();
			driver.findElement(By.xpath("//h3[text()='Overall Sales Report']")).click();
			driver.findElement(By.xpath("(//div[@class='reportrange'])[1]")).click();
			driver.findElement(By.xpath("//div[@class='ranges']//ul//li[text()='Custom Range']")).click();
			driver.findElement(By.xpath("(//div[@class=\"drp-calendar left\"]//tbody//tr//td[text()='1'])[1]")).click();
        	driver.findElement(By.xpath("(//div[@class=\"drp-calendar right\"]//tbody//tr//td[text()='3'])[1]")).click();
        	driver.findElement(By.xpath("//button[text()='Apply']")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[1]")).click();
        	Thread.sleep(1000);
        	driver.findElement(By.xpath("//h3[text()='Warehouse Hourly Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[2]")).click();
        	driver.findElement(By.xpath("(//div[@class='ranges']//ul//li[text()='Today'])[2]")).click();
        	WebElement Sortinghub=driver.findElement(By.xpath("//select[@name='sorting_hub_id']"));
			Select select =new Select(Sortinghub);
			select.selectByVisibleText("Raebareli Sorting Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[2]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Call Center performance report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[3]")).click();
			driver.findElement(By.xpath("(//div[@class='ranges']//ul//li[text()='Custom Range'])[3]")).click();
			driver.findElement(By.xpath("(//div[@class='drp-calendar right']//tbody//tr//td[text()='1'])[5]")).click();
        	driver.findElement(By.xpath("(//div[@class='drp-calendar right']//tbody//tr//td[text()='20'])[3]")).click();
        	driver.findElement(By.xpath("(//button[text()='Apply'])[3]")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[3]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='EoD WH tracker']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[4]")).click();
        	driver.findElement(By.xpath("(//div[@class='ranges']//ul//li[text()='Today'])[4]")).click();
        	WebElement Sortinghub1=driver.findElement(By.xpath("(//select[@name='sorting_hub_id'])[2]"));
			Select select1 =new Select(Sortinghub1);
			select1.selectByVisibleText("Rural Lucknow");
        	driver.findElement(By.xpath("(//button[@type='submit'])[4]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Warehouse Monthly Sales Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[5]")).click();
        	driver.findElement(By.xpath("(//div[@class='ranges']//ul//li[text()='Today'])[5]")).click();
        	WebElement Sortinghub2=driver.findElement(By.xpath("(//select[@name='sorting_hub_id'])[3]"));
			Select select2 =new Select(Sortinghub2);
			select2.selectByVisibleText("Amethi Sorting Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[5]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='CC Day end sales Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[6]")).click();
        	driver.findElement(By.xpath("(//div[@class='ranges']//ul//li[text()='Today'])[6]")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[6]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='EOD Warehouse Margin Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[7]")).click();
        	driver.findElement(By.xpath("(//div[@class='ranges']//ul//li[text()='Today'])[7]")).click();
        	WebElement Sortinghub3=driver.findElement(By.xpath("(//select[@name='sorting_hub_id'])[4]"));
			Select select3 =new Select(Sortinghub3);
			select3.selectByVisibleText("Jhajjar Sorting Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[7]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Toast report (Clusterwise)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[8]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[8]")).click();
        	WebElement Cluster=driver.findElement(By.xpath("//select[@name='cluster_id']"));
        	Select select4=new Select(Cluster);
        	select4.selectByVisibleText("Up Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[8]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Sambhar salt report (Clusterwise)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[9]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[9]")).click();
        	WebElement Sambharsalt=driver.findElement(By.xpath("(//select[@name='cluster_id'])[2]"));
        	Select select5=new Select(Sambharsalt);
        	select5.selectByVisibleText("Haryana Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[9]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Sambhar salt + khal report (Warehouse-FO wise)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[10]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[10]")).click();
        	WebElement khal=driver.findElement(By.xpath("(//select[@name='sorting_hub_id'])[5]"));
        	Select select6=new Select(khal);
        	select6.selectByVisibleText("Raebareli Sorting Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[10]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='FO wise sale Report (Clusterwise)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[11]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[11]")).click();
        	WebElement FO=driver.findElement(By.xpath("(//select[@name='cluster_id'])[3]"));
        	Select select7=new Select(FO);
        	select7.selectByVisibleText("Up Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[11]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='EOD FO wise sale Report (Haryana)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[12]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[12]")).click();
        	WebElement EODFO=driver.findElement(By.xpath("(//select[@name='cluster_id'])[4]"));
        	Select select8=new Select(EODFO);
        	select8.selectByVisibleText("Up Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[12]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='FO Blockwise Sale Report (Clusterwise)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[13]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[13]")).click();
        	WebElement FOBlockwise=driver.findElement(By.xpath("(//select[@name='cluster_id'])[5]"));
        	Select select9=new Select(FOBlockwise);
        	select9.selectByVisibleText("Up Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[13]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Sales Return Blockwise Report (Clusterwise)']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[14]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[14]")).click();
        	WebElement Sales=driver.findElement(By.xpath("(//select[@name='cluster_id'])[6]"));
        	Select select10=new Select(Sales);
        	select10.selectByVisibleText("Up Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[14]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='CC Executive Performance Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[15]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[15]")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[15]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Calling Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[16]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[16]")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[16]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='PNA Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[17]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[17]")).click();
        	WebElement PNA=driver.findElement(By.xpath("(//select[@name='cluster_id'])[7]"));
        	Select select11=new Select(PNA);
        	select11.selectByVisibleText("Up Cluster Hub");
        	driver.findElement(By.xpath("(//button[@type='submit'])[17]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Cancellation Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[18]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[18]")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[18]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Footwear FO Performance Report']")).click();
        	driver.findElement(By.xpath("(//div//input[@type='month'])[1]")).sendKeys("November,2024");
        	WebElement type=driver.findElement(By.xpath("(//select[@name='type'])[1]"));
        	Select select12=new Select(type);
        	select12.selectByVisibleText("Half Yearly");
        	//driver.findElement(By.xpath("(//button[@type='submit'])[19]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Footwear Sales - Sorting Hub Report']")).click();
        	driver.findElement(By.xpath("(//div//input[@type='month'])[2]")).sendKeys("November,2024");
        	WebElement type1=driver.findElement(By.xpath("(//select[@name='type'])[2]"));
        	Select select13=new Select(type1);
        	select13.selectByVisibleText("Half Yearly");
        	driver.findElement(By.xpath("(//button[@type='submit'])[20]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Footwear Active Peer Report']")).click();
        	driver.findElement(By.xpath("(//button[@type='submit'])[21]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Funnel Report (By Category)']")).click();
        	driver.findElement(By.xpath("(//div//input[@type='month'])[3]")).sendKeys("October,2024");
        	WebElement OrderCount=driver.findElement(By.xpath("(//select[@name='type'])[3]"));
        	Select select14=new Select(OrderCount);
        	select14.selectByVisibleText("Order Count");
        	WebElement category=driver.findElement(By.xpath("//select[@name='category']"));
        	Select select15=new Select(category);
        	select15.selectByVisibleText("Grocery & Staple");
        	driver.findElement(By.xpath("(//button[@type='submit'])[23]")).click();
        	Thread.sleep(5000);
        	driver.findElement(By.xpath("//h3[text()='Darkstore Express Delivery Hourly Sales Report']")).click();
        	driver.findElement(By.xpath("(//div[@class='reportrange'])[19]")).click();
        	driver.findElement(By.xpath("(//div//ul/li[text()='Last 2 Days'])[19]")).click();
        	driver.findElement(By.xpath("//div//input[@type='time']")).sendKeys("19:31");
        	WebElement sortinghubid=driver.findElement(By.xpath("//select[@name='sorting_hub_id[]']"));
        	Select select16=new Select(sortinghubid);
        	select16.selectByVisibleText("Amethi_ds1");
        	driver.findElement(By.xpath("(//button[@type='submit'])[24]")).click();
			//Logout
            Thread.sleep(5000);
            driver.findElement(By.xpath("//i[@class='demo-pli-male']/ancestor::li[@id='dropdown-user']")).click();
            Thread.sleep(5000);
           driver.findElement(By.xpath("//a[@href='https://dev.rozana.in/logout']")).click();

}};
